# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 1

# Personal info
name: Рустам Шайдуллов
title: Ryby on Rails Developer
email: 28rustam@gmail.com
phone: 9872947036

# Social links
twitter_username: russell_ocean
github_username:  rust-am
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: rustamshaidullov
linkedin_username: rust-am
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Привет, меня зовут Рустам, я геолог который хочет стать <mark>Ruby on Rails</mark> веб-разработчиком. 
  В настоящее время учусь ...

  <u>Языки</u>

  Английский - intermediate

  Японский - basic

# Projects Section
# projects_title: Projects

#Experience Section
experience_title: Experience

#Education Section
educaton_title: Education

technical_title: Technical Expertise

# More Section
# more_title: A Little More About Me
# more_content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: true

# Build settings
#theme: modern-resume-theme
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
