# Site
repository: rust-am/cv-rus
favicon: images/favicon.ico

version: 1

# Personal info
name: Рустам Шайдуллов
title: Ryby on Rails Developer
email: 28rustam@gmail.com
phone: 9872947036

# Social links
twitter_username: russell_ocean
github_username:  rust-am
# dribbble_username:
# facebook_username:
# flickr_username:
instagram_username: rustamshaidullov
linkedin_username: rust-am
# pinterest_username:
# youtube_username:
# googleplus_username:

# About Section
# about_title: About Me
about_profile_image: images/jg.jpg
about_content: |
  Привет, меня зовут Рустам, я геолог который хочет стать <mark>Ruby on Rails</mark> веб-разработчиком. 
  В настоящее время учусь ...

content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: middle
        title: barbecue
        link: http://barbecue.ru.com
        link_text: Link Text
        additional_links:
          - title:  rust-am/barbecue
            icon: fab fa-github
            url: rust-am/barbecue
        quote: >
              Сайт где легко можно создать мероприятие и позвать на него всех друзей!
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project
      - layout: middle
        title: askmee
        link: http://askmee.herokuapp.com
        link_text: Link Text
        additional_links:
          - title:  rust-am/barbecue
            icon: fab fa-github
            url: rust-am/barbecue
        quote: >
              Сайт где легко можно создать мероприятие и позвать на него всех друзей!
        description: | # this will include new lines to allow paragraphs
          Description about the work on/with the project

  - title: skils
    layout: list
    content:
      - title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: Experience
    layout: list
    content:
      - title: Company name
        sub_title: Job title
        caption: Date Range (eg. November 2016 - present)
        link: Link to company (optional)
        quote: >
          Short description of the company (optional)
        description: | # this will include new lines to allow paragraphs
          Description of role

  - title: Education
    layout: list
    content:
      - title: Institution name
        sub_title: Qualifications (eg. BA Performing Arts)
        caption: Date Range (eg. 2016 - 2019)
        quote: >
          Short institution or course description (optional)
        description: | # this will include new lines to allow paragraphs
          Description of qualification

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

# sass:
#   style: compressed
